// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOc0a9IH3bLtVO8NPl9-dupDR8Tni-WY',
    appId: '1:132651455240:web:32f1e7edb9c11d324912bd',
    messagingSenderId: '132651455240',
    projectId: 'sayara-hub-app',
    authDomain: 'sayara-hub-app.firebaseapp.com',
    storageBucket: 'sayara-hub-app.firebasestorage.app',
    measurementId: 'G-4TEEMDWH7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtq8rVYx0L620OaIjW9_dIvHu8T4UQMQ4',
    appId: '1:132651455240:android:9643ad26903eaf4e4912bd',
    messagingSenderId: '132651455240',
    projectId: 'sayara-hub-app',
    storageBucket: 'sayara-hub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNx6zpdw08NmePZvX8ISvzxPzchAFNDmE',
    appId: '1:132651455240:ios:8fc2b0cb53f9a75e4912bd',
    messagingSenderId: '132651455240',
    projectId: 'sayara-hub-app',
    storageBucket: 'sayara-hub-app.firebasestorage.app',
    iosBundleId: 'com.example.sayaraHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNx6zpdw08NmePZvX8ISvzxPzchAFNDmE',
    appId: '1:132651455240:ios:8fc2b0cb53f9a75e4912bd',
    messagingSenderId: '132651455240',
    projectId: 'sayara-hub-app',
    storageBucket: 'sayara-hub-app.firebasestorage.app',
    iosBundleId: 'com.example.sayaraHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHOc0a9IH3bLtVO8NPl9-dupDR8Tni-WY',
    appId: '1:132651455240:web:11ba67de6109628c4912bd',
    messagingSenderId: '132651455240',
    projectId: 'sayara-hub-app',
    authDomain: 'sayara-hub-app.firebaseapp.com',
    storageBucket: 'sayara-hub-app.firebasestorage.app',
    measurementId: 'G-V3WVZBY076',
  );
}
